version: '{branch}-{build}'
image: Visual Studio 2019
configuration: Release
platform: x64
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME-$env:APPVEYOR_BUILD_NUMBER"
    }
    else
    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))-$env:APPVEYOR_BUILD_NUMBER"
    }
environment:
  QTDIR: C:\Qt\5.12.6\msvc2017_64
  OPENSSL: C:\OpenSSL-v111-Win64\bin
  nodejs_version: "LTS"
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: cd "C:\projects\pta\PTA\search\" && npm ci
build_script:
  - cmd: msbuild "C:\projects\pta\PTA.sln" /m /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:QtInstall=%QTDIR%
  - cmd: cd "C:\projects\pta\PTA\search\" && npm run build
after_build:
- ps: .\deploy\package.ps1
